export const OBTENER_CRIPTOMONEDAS = 'OBTENER_CRIPTOMONEDAS';
export const OBTENER_CRIPTOMONEDAS_EXITO = 'OBTENER_CRIPTOMONEDAS_EXITO';
export const OBTENER_CRIPTOMONEDAS_FRACASO = 'OBTENER_CRIPTOMONEDAS_FRACASO';

export const OBTENER_CRIPTOMONEDA = 'OBTENER_CRIPTOMONEDA';
export const OBTENER_CRIPTOMONEDA_EXITO = 'OBTENER_CRIPTOMONEDA_EXITO';
export const OBTENER_CRIPTOMONEDA_FRACASO = 'OBTENER_CRIPTOMONEDA_FRACASO';

export const OBTENER_VARIACION = 'OBTENER_VARIACION';
export const OBTENER_VARIACION_EXITO = 'OBTENER_VARIACION_EXITO';
export const OBTENER_VARIACION_FRACASO = 'OBTENER_VARIACION_FRACASO';

export const OBTENER_VARIACION_24HORAS = 'OBTENER_VARIACION_24HORAS';
export const RECETEAR_ESTADOS_GLOBALES = 'RECETEAR_ESTADOS_GLOBALES';

export const RECETEAR_VARIACION_24HORAS = 'RECETEAR_VARIACION_24HORAS';

export const CRIPTOMONEDAS_MERCADOS = 'CRIPTOMONEDAS_MERCADOS';
export const CRIPTOMONEDAS_MERCADOS_EXITO = 'CRIPTOMONEDAS_MERCADOS_EXITO';
export const CRIPTOMONEDAS_MERCADOS_FRACASO = 'CRIPTOMONEDAS_MERCADOS_FRACASO';